apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link-prometheus: http://localhost:30000
    link.argocd.argoproj.io/external-link-grafana: http://localhost:31000
    link.argocd.argoproj.io/external-link-alertmanager: http://localhost:32000
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 55.5.0
    helm:
      values: |-
        prometheus:
          prometheusSpec:
            retention: 7d
          service:
            type: NodePort
            nodePort: 30000

        alertmanager:
          service:
            type: NodePort
            nodePort: 32000
        
        grafana:
          service:
            type: NodePort
            nodePort: 31000
          adminPassword: admin123

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 15m
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
