# Argo CD Helm values with custom Helm v3.12.3
metrics:
  enabled: true

admin:
  enabled: true

applicationSet:
  enabled: true

resourceTrackingMethod: annotation

rbac:
  enabled: true

notifications:
  enabled: true

audit:
  enabled: true

dex:
  enabled: false

server:
  insecure: false
  disable:
    auth: false

# Configure repo server with custom Helm v3.12.3 using official custom tooling
repoServer:
  volumes:
    - name: custom-tools
      emptyDir: {}
  
  initContainers:
    - name: download-helm
      image: alpine:3.18
      command: [sh, -c]
      args:
        - wget -qO- https://get.helm.sh/helm-v3.12.3-linux-amd64.tar.gz | tar -xvzf - &&
          mv linux-amd64/helm /custom-tools/ &&
          chmod +x /custom-tools/helm &&
          echo "Helm v3.12.3 downloaded successfully"
      volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools
  
  volumeMounts:
    - name: custom-tools
      mountPath: /usr/local/bin/helm
      subPath: helm

configs:
  cm:
    # Enable metrics
    metrics.enabled: "true"
    
    # Configure admin user
    admin.enabled: "true"
    
    # Enable application set controller
    applicationSet.enabled: "true"
    
    # Configure resource tracking
    resourceTrackingMethod: annotation
    
    # Enable RBAC
    rbac.enabled: "true"
    
    # Configure notifications
    notifications.enabled: "true"
    
    # Configure audit logging
    audit.enabled: "true"
    
    # Configure server settings
    server.insecure: "false"
    server.disable.auth: "false"
    
    # Configure repositories
    repositories: |
      - type: git
        url: https://github.com/csz-devops/kind-argosy.git
        name: kind-argosy
      - type: helm
        url: https://prometheus-community.github.io/helm-charts
        name: prometheus-community
