apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.2.7
    helm:
      values: |
        # Enable metrics for monitoring
        metrics:
          enabled: true
        
        # Configure admin user
        admin:
          enabled: true
        
        # Enable application set controller
        applicationSet:
          enabled: true
        
        # Configure resource tracking
        resourceTrackingMethod: annotation
        
        # Enable RBAC
        rbac:
          enabled: true
        
        # Configure notifications
        notifications:
          enabled: true
        
        # Enable audit logging
        audit:
          enabled: true
        
        # Configure server settings
        server:
          insecure: false
          disable:
            auth: false
        
        # Configure repo server with custom Helm version
        repoServer:
          # Custom Helm version configuration
          extraInitContainers:
            - name: install-helm
              image: alpine:3.18
              command:
                - sh
                - -c
                - |
                  wget -O /helm.tar.gz https://get.helm.sh/helm-v3.12.3-linux-amd64.tar.gz
                  tar -xzf /helm.tar.gz
                  cp linux-amd64/helm /shared/helm
                  chmod +x /shared/helm
                  /shared/helm version
              volumeMounts:
                - name: helm-volume
                  mountPath: /shared
          
          extraVolumeMounts:
            - name: helm-volume
              mountPath: /usr/local/bin/helm
              subPath: helm
          
          extraVolumes:
            - name: helm-volume
              emptyDir: {}
          
          env:
            - name: HELM_VERSION
              value: "v3.12.3"
        
        # Configure configmap settings
        configs:
          cm:
            # Enable metrics
            metrics.enabled: "true"
            
            # Configure admin user
            admin.enabled: "true"
            
            # Enable application set controller
            applicationSet.enabled: "true"
            
            # Configure resource tracking
            resourceTrackingMethod: annotation
            
            # Enable RBAC
            rbac.enabled: "true"
            
            # Configure notifications
            notifications.enabled: "true"
            
            # Enable audit logging
            audit.enabled: "true"
            
            # Configure server settings
            server.insecure: "false"
            server.disable.auth: "false"
            
            # Enable dex for SSO (optional)
            dex.enabled: "false"
            
            # Configure repository credentials
            repositories: |
              - type: git
                url: https://github.com/csz-devops/kind-argosy.git
                name: kind-argosy
              - type: helm
                url: https://prometheus-community.github.io/helm-charts
                name: prometheus-community
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
