# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argocd
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
#   annotations:
#     argocd.argoproj.io/sync-wave: "0"
# spec:
#   project: default
#   source:
#     repoURL: https://argoproj.github.io/argo-helm
#     chart: argo-cd
#     targetRevision: 8.2.7
#     # helm:
#     #   values: |
#     #     # Configure repo server with custom Helm v3.12.3
#     #     repoServer:
#     #       volumes:
#     #         - name: custom-tools
#     #           emptyDir: {}
          
#     #       initContainers:
#     #         - name: download-helm
#     #           image: alpine:3.18
#     #           command: [sh, -c]
#     #           args:
#     #             - wget -qO- https://get.helm.sh/helm-v3.12.3-linux-amd64.tar.gz | tar -xvzf - &&
#     #               mv linux-amd64/helm /custom-tools/ &&
#     #               chmod +x /custom-tools/helm &&
#     #               echo "Helm v3.12.3 downloaded successfully"
#     #           volumeMounts:
#     #             - name: custom-tools
#     #               mountPath: /custom-tools
          
#     #       volumeMounts:
#     #         - name: custom-tools
#     #           mountPath: /usr/local/bin/helm
#     #           subPath: helm
        
#     #     # Configure repositories
#     #     configs:
#     #       cm:
#     #         dex.enabled: "false"
#     #         repositories: |
#     #           - type: git
#     #             url: https://github.com/csz-devops/kind-argosy.git
#     #             name: kind-argosy
#     #           - type: helm
#     #             url: https://prometheus-community.github.io/helm-charts
#     #             name: prometheus-community
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: argocd
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#       allowEmpty: true
#     retry:
#       limit: 10
#       backoff:
#         duration: 30s
#         factor: 2
#         maxDuration: 15m
#     syncOptions:
#       - CreateNamespace=true
#       - PrunePropagationPolicy=foreground
#       - PruneLast=true
#       - ApplyOutOfSyncOnly=true
#       - ServerSideApply=true
