apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.0.12/manifests/install.yaml

patches:
- target:
    kind: Deployment
    name: argocd-repo-server
  patch: |-
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: helm-working-dir
        emptyDir: {}
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        name: helm-working-dir
        mountPath: /helm-working-dir
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: HELM_CACHE_HOME
        value: /helm-working-dir
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: HELM_CONFIG_HOME
        value: /helm-working-dir
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: HELM_DATA_HOME
        value: /helm-working-dir
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: HELM_VERSION
        value: v3.12.3
    - op: add
      path: /spec/template/spec/initContainers/-
      value:
        name: install-helm
        image: alpine:3.18
        volumeMounts:
        - name: helm-working-dir
          mountPath: /helm-working-dir
        env:
        - name: HELM_CACHE_HOME
          value: /helm-working-dir
        - name: HELM_CONFIG_HOME
          value: /helm-working-dir
        - name: HELM_DATA_HOME
          value: /helm-working-dir
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk --no-cache add curl;
          wget -O /helm.tar.gz https://get.helm.sh/helm-v3.12.3-linux-amd64.tar.gz;
          tar -xzf /helm.tar.gz;
          rm -f /usr/local/bin/helm;
          cp linux-amd64/helm /usr/local/bin/helm;
          chmod +x /usr/local/bin/helm;
          chmod -R 777 /helm-working-dir;
          echo "=== HELM VERSION CHECK ===";
          /usr/local/bin/helm version;
          echo "=== WHICH HELM ===";
          which helm;
          echo "=== HELM VERSION FROM PATH ===";
          helm version;

configMapGenerator:
- name: argocd-cm
  behavior: merge
  literals:
  - metrics.enabled=true
  - admin.enabled=true
  - applicationSet.enabled=true
  - resourceTrackingMethod=annotation
  - rbac.enabled=true
  - notifications.enabled=true
  - audit.enabled=true
  - server.insecure=false
  - server.disable.auth=false
  - |
    repositories=|
    - type: git
      url: https://github.com/csz-devops/kind-argosy.git
      name: kind-argosy
    - type: helm
      url: https://prometheus-community.github.io/helm-charts
      name: prometheus-community
